M48
; DRILL file {KiCad 7.0.2-6a45011f42~172~ubuntu22.04.1} date Thu 11 May 2023 11:42:12 AM -04
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-11T11:42:12-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-6a45011f42~172~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1693
%
G90
G05
T1
X2.99Y-2.84
X8.03Y-2.85
T0
M30
